"""
An ISO 8601-encoded datetime
"""
scalar ISO8601DateTime @specifiedBy(url: "https://tools.ietf.org/html/rfc3339")

type Mutation {
  """
  Mutation-surface health check.
  """
  ping: String!
  setProductActive(
    """
    Parameters for SetProductActive
    """
    input: SetProductActiveInput!
  ): SetProductActivePayload
}

"""
Information about pagination in a connection.
"""
type PageInfo {
  """
  When paginating forwards, the cursor to continue.
  """
  endCursor: String

  """
  When paginating forwards, are there more items?
  """
  hasNextPage: Boolean!

  """
  When paginating backwards, are there more items?
  """
  hasPreviousPage: Boolean!

  """
  When paginating backwards, the cursor to continue.
  """
  startCursor: String
}

type Product {
  active: Boolean!
  createdAt: ISO8601DateTime!
  description: String
  id: ID!
  name: String!
  sku: String!
  unitOfMeasure: String
}

"""
The connection type for Product.
"""
type ProductConnection {
  """
  A list of edges.
  """
  edges: [ProductEdge]

  """
  A list of nodes.
  """
  nodes: [Product]

  """
  Information to aid in pagination.
  """
  pageInfo: PageInfo!
}

"""
An edge in a connection.
"""
type ProductEdge {
  """
  A cursor for use in pagination.
  """
  cursor: String!

  """
  The item at the end of the edge.
  """
  node: Product
}

type Query {
  """
  Products in the current tenant.
  """
  products(
    """
    Filter by active flag.
    """
    active: Boolean

    """
    Returns the elements in the list that come after the specified cursor.
    """
    after: String

    """
    Returns the elements in the list that come before the specified cursor.
    """
    before: String

    """
    Returns the first _n_ elements from the list.
    """
    first: Int

    """
    Returns the last _n_ elements from the list.
    """
    last: Int

    """
    Search name/SKU.
    """
    query: String
  ): ProductConnection!

  """
  The current user and their role in this tenant.
  """
  viewer: Viewer
}

"""
Autogenerated input type of SetProductActive
"""
input SetProductActiveInput {
  active: Boolean!

  """
  A unique identifier for the client performing the mutation.
  """
  clientMutationId: String
  id: ID!
}

"""
Autogenerated return type of SetProductActive.
"""
type SetProductActivePayload {
  """
  A unique identifier for the client performing the mutation.
  """
  clientMutationId: String
  product: Product
  userErrors: [UserError!]!
}

type UserError {
  code: String!
  field: String
  message: String!
}

type Viewer {
  """
  Current user's email.
  """
  email: String

  """
  The user's role in this tenant.
  """
  role: String

  """
  The resolved tenant.
  """
  tenantSubdomain: String
}
